### ISSUE TITLE
.travis.yml should use proper node syntax

### ISSUE THREAD

**Issue by mmalecki** [raoulmillais/node-7digital-api#14]
Please see: http://about.travis-ci.org/docs/user/languages/javascript-with-nodejs/
I think that it should look like:

``` yml
language: node_js
node_js:
  - 0.4
  - 0.6

notifications:
  email:
    - tony.to@7digital.com
    - raoul.millais@7digital.com

before_script: "git submodule update --init --recursive"
```
